### ISSUE TITLE
orc.csres.utexas.edu vs. orc-lang.org is causing certificate problems

### ISSUE THREAD

**Issue by arthurp** [orc-lang/orc#144]
The Orc server uses an SSL certificate for orc.csres.utexas.edu. Which is all well and good except we are also serving on orc-lang.org.

The problem become most visible in the wiki because clicking Edit or Login (correctly) redirects to an https URL.

We should probably standardize on one domain name and make the others redirect to that one. Then we can just have the SSL key setup for that one (since as far as I know there is no way to support multiple https domains on the same IP address).

To reproduce go to: http://www.orc-lang.org/wiki/ and click login or edit.

**Comment by jthywiss** [comment]
Done.

**Comment by jthywiss** [comment]
I adjusted the domain forwarding settings for orc-lang at our DNS registrar.
