### ISSUE TITLE
Remove googlecode references from all build scripts

### ISSUE THREAD

**Issue by arthurp** [orc-lang/orc#152]
These tools are no longer useful, so we should remove the references including:
- [ ] jars
- [ ] licenses
- [ ] build targets
- [ ] config files (if there are any)

**Comment by jthywiss** [comment]
Need to replace with a GitHub equivalent Ant task

**Comment by arthurp** [comment]
This should wait until after completion of #200 to avoid duplication of effort.

**Comment by jthywiss** [comment]
Fixed in dcd01479d09de34ddbe5dc5d273a397770c44a7a
