### ISSUE TITLE
Add automatic testing for d-Orc

### ISSUE THREAD

**Issue by arthurp** [orc-lang/orc#175]
Currently d-Orc can only be tested manually. We should come up with a way to test it automatically. I'm pretty concerned about breaking d-Orc totally during the object work that is to come.

We may be able to use some of the code from the d-Orc paper Java benchmarks as a basis for code to start/stop the needed d-Orc instances in the test harness.

**Comment by jthywiss** [comment]
Closed by 55d79cb4bf0ebda14c2f1c3d374d21154c6ce59b
