### ISSUE TITLE
Update quickstart with new VCS information

### ISSUE THREAD

**Issue by jkdf2** [orc-lang/orc#186]
The [quickstart](https://orc.csres.utexas.edu/quickstart.shtml) recommends SVN and downloading code from googlecode. Unless I am mistaken, this should be updated to recommending git and downloading from this GitHub repo, right?

**Comment by arthurp** [comment]
Yes it should. The website is stored in the "Website" directory of this repo. I think the static HTML stuff is pretty self explanatory. Feel free to make a PR (or just commit if you are confident it is correct) it will not go live automatically or anything.

**Comment by jthywiss** [comment]
Fixed in ae687e23dc068fd20a9a79688fe7e2ba61bb6a8b
