### ISSUE TITLE
Rename orc.Handle to orc.CallContext

### ISSUE THREAD

**Issue by jthywiss** [orc-lang/orc#201]
From discussion on https://github.com/orc-lang/orc/pull/199#discussion_r127056422:

`orc.Handle` is vaguely named. It is an interface for a site call instance to interact with the Orc runtime, primarily to send responses.  Rename to `SiteResponseChannel`?  Well maybe not "Channel", but something like that....

**Comment by jthywiss** [comment]
Maybe "orc.SiteResponseInterface"?

**Comment by arthurp** [comment]
"orc.SiteResponseInterface" sounds like the interface for a site response. Also it should be "Method" not "Site" if we are trying to switch to the new terms. 

How about "orc.MethodResponseHandler"? 

That does describe exactly what that object does. It handles method responses.

**Comment by jthywiss** [comment]
CallResponseReceiver ?
Caller ?

**Comment by jthywiss** [comment]
CallContext !
