### ISSUE TITLE
Improve compatibility of distributed test cases

### ISSUE THREAD

**Issue by arthurp** [orc-lang/orc#209]
The distributed test harness currently spawns terminal instances for subprocess output and fails if that cannot be done. This is problematic because it requires special handling for each desktop environment and is totally impossible in environments without a GUI (for instance, a CI system, though obviously the CI setup would also have problems because of the need to log into CS linux machines).

The test harness should be able to just send the command output to log files on disk. This would allow the test to run many more environments. I actually this this should be the default (with the terminal spawning behavior being enabled by a java -D flag). The reason is that most test runs can be done in the background while doing other things and spawning the terminals gets in the way of that (at least on linux), also the logs could be analysed more easily if they can be rerouted files and post processed.

This issue is still a problem in b1832f06253a1242c8b7ac7e3513556947c8703b.

**Comment by arthurp** [comment]
@jthywiss I think you have now fixed this. Is that correct? If so you could have the join of closing this issue. :-)

**Comment by jthywiss** [comment]
Closed by 86d253614fbe70a62d303daf83c8ca3d11dc21c1
